<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkout1</name>
   <tag></tag>
   <elementGuidId>03fd0f6b-920c-4f34-b959-7f9334a03f9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;msform&quot;]/fieldset/div/div[2]/div[3]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;msform&quot;]/fieldset/div/div[2]/div[3]/div[2]/a</value>
   </webElementProperties>
</WebElementEntity>
