<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Premier</name>
   <tag></tag>
   <elementGuidId>05427611-c62f-476b-bfae-4a6ae3377ac7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;msform&quot;]/fieldset/div/div[2]/table/tbody/tr[2]/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;msform&quot;]/fieldset/div/div[2]/table/tbody/tr[2]/td[1]</value>
   </webElementProperties>
</WebElementEntity>
